version: 2
jobs:
  build:
    working_directory: ~/banklink
    docker:
      # Ruby 2.1.10
      - image: circleci/ruby@sha256:e49f95920f6294593e99cd6401556a36a8b47703b5bdac0b094b66ae1cdd6569
        environment:
          TZ: "/usr/share/zoneinfo/Europe/Riga"
          RAILS_ENV: test
          COV: "false"

    steps:
      - checkout

      - run: gem install bundler -v 1.16.2 --no-doc

      - restore_cache:
          key: v1-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path ~/vendor/bundle

      #== save caches ==

      - save_cache:
          key: v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/vendor/bundle

      # == run specs ==

      - run: rspec spec/
