version: 2

defaults: &defaults
  working_directory: ~/banklink
  docker:
    - image: circleci/ruby:2.3.8-node-browsers
      environment:
        TZ: "/usr/share/zoneinfo/Europe/Riga"
        RAILS_ENV: test
        COV: "false"

jobs:
  bundle_install:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/banklink

      - restore_cache:
          key: bundle-{{ arch }}-{{ checksum "Gemfile" }}

      - run:
          name: Install bundler
          command: gem install bundler -v 1.17.3 --no-doc

      - run:
          name: Bundle Check
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - save_cache:
          key: bundle-{{ arch }}-{{ checksum "Gemfile" }}
          paths:
            - ~/vendor/bundle

      - persist_to_workspace:
          root: .
          paths: vendor/bundle

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/banklink
      - run: bundle install --path vendor/bundle

      - run:
          name: Run RSpec
          command: bundle exec rspec spec

workflows:
  version: 2
  build:
    jobs:
      - bundle_install
      - test:
          requires:
            - bundle_install
