name: Test

on: pull_request

env:
  TZ: "/usr/share/zoneinfo/Europe/Riga"
  RAILS_ENV: test
  COV: "false"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.3
        bundler-cache: true
        
    - name: Install dependencies
      run: bundle install
      
    - name: Run tests
      run: bundle exec rspec spec
